config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'my_devise/omniauth_callbacks', registrations: 'my_devise/registrations' }

  get '/', to: 'application#index'
  # patch '/mining_rig/:id/miners', to: 'miners#mining'
  get '/users/highest_balance', to: 'users#highest_balance', as: 'highest_balance'


  resources :energy_packs
  resources :coins


  resources :users do
    resources :wallets, only: [:show, :update]
    resources :mining_rigs
  end
  patch '/mining_rig/:id/miners', to: 'miners#update'
end

app/models/mining_rig.rb
class MiningRig < ApplicationRecord
  belongs_to :user
  has_many :mining_rig_miners
  has_many :miners, through: :mining_rig_miners

  validates_presence_of :name, on: :create
  validates_presence_of :mining_rig_miners, on: :create, message: 'are invalid'
  validate :miners_count_limit, on: :update
  validates_presence_of :mining_rig_miners

  def mining_rig_miners_attributes=(mining_rig_miners_attributes)
    mining_rig_miners_attributes.each_value do |mining_rig_miners_attribute|
      if !mining_rig_miners_attribute[:hash_rate].empty?
        miner = Miner.create(hash_rate: mining_rig_miners_attribute[:hash_rate])
        mining_rig_miner = self.mining_rig_miners.build
        mining_rig_miner.update(mining_rig_miners_attribute)
        mining_rig_miner.miner_id = miner.id
        mining_rig_miner.save
      end
    end
  end

  def status
    miners.any?{ |miner| miner.status == true }
  end

  def total_miners
    miners.count
  end

  def change_status
    miners.each do |miner|
      if miner.status
        miner.status = false
      else
        miner.status = true
      end
      miner.save
    end
  end

  def total_cosumption
    total = 0
    miners.each{ |miner| total += miner.consumption }
    total
  end

  def total_hashrate
    total = 0
    miners.each{ |miner| total += miner.hash_rate }
    total
  end

  private

  def miners_count_limit
    return if miners.blank?
    errors.add(:miners, 'Limit reached') if miners.size > 5
  end
  handle_asynchronously :change_status, :run_at => Proc.new { 5.minutes.from_now }
end

app/controllers/mining_rigs_controller.rb
class MiningRigsController < ApplicationController
  before_action :set_mining_rig, only: [:edit, :update, :show]
  def index
    @mining_rigs = current_user.mining_rigs

    respond_to do |format|
      format.html { render 'index'}
      format.json { render json: @mining_rigs, status: 200}
    end
  end

  def new
    @mining_rig = current_user.mining_rigs.build
    @mining_rig_miner = @mining_rig.mining_rig_miners.build
  end

  def create
    @mining_rig = current_user.mining_rigs.build(mining_rig_params)
    hash_rate = params["mining_rig"]["mining_rig_miners_attributes"]["0"]["hash_rate"].to_i

    if enough_balance?(hash_rate)
      binding.pry
      if @mining_rig.save
        miner = @mining_rig.miners.last

        current_user.balance -= miner.price
        current_user.save
        @mining_rigs = current_user.mining_rigs

        flash[:success] = 'You succesfully created a Miner for your Mining Rig'
        render json: @mining_rigs

      else
        flash[:error] = @mining_rig.errors.full_messages.to_sentence
        render :new, status: 221
      end
    else
      flash[:error] = 'You do not have enough balance'
      render :new
    end
  end

  def edit
    @mining_rig_miner = @mining_rig.mining_rig_miners.build
  end

  def update
    binding.pry
    hash_rate = params["mining_rig"]["mining_rig_miners_attributes"]["0"]["hash_rate"].to_i

    if @mining_rig.update(mining_rig_params)
      @miner = @mining_rig.miners.last

      if !enough_balance?(hash_rate)
        flash[:error] = 'You do not have enough balance'
        redirect_to edit_user_mining_rig_path(current_user)
      else
        @miner = @mining_rig.miners.last
        current_user.balance -= @miner.price
        current_user.save
        flash[:success] = 'Mining Rig succesfully updated'
        redirect_to user_mining_rigs_path(current_user)
      end
    else
      flash[:error] = @mining_rig.errors.full_messages.to_sentence
      redirect_to edit_user_mining_rig_path(current_user)
    end
  end

  def show
    @mining_rig_miners = @mining_rig.mining_rig_miners
    @miners = @mining_rig.miners

    respond_to do |format|
      format.html { render 'show'}
      format.json { render json: @miners, status: 200}
    end
  end

  private

  def mining_rig_params
    params.require(:mining_rig).permit(:name, :user_id, mining_rig_miners_attributes: [:hash_rate, :brand])
  end

  def set_mining_rig
    @mining_rig = MiningRig.find(params[:id])
  end
end

app/helpers/mining_rigs_helper.rb
module MiningRigsHelper
end

app/views/mining_rigs/_form.html.erb
<%= form_for [current_user, mining_rig], html: {  class: 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><strong>Mining Rig of <%= current_user.username %></strong></legend>
      <div class="form-group">
        <%= f.label 'Mining Rig', class: 'col-md-4 control-label' %>
        <div class="col-md-4">
          <div class="input-group">
            <span class="input-group-addon">Name:</span>
            <%= f.text_field :name, required: "required", class: 'form-control', placeholder: 'Antyhing you want' %>
          </div>
        </div>
      </div>

      <div class="col-md col-md-offset-4">
          <h3>Create a new Miner for this Mining Rig</h3>

          <p><%= number_to_currency(1000) %>USD, will get you 56TH/s</p>
          <p><%= number_to_currency(500) %>USD, will get you 28TH/s</p>
          <p><%= number_to_currency(250) %>USD, will get you 14TH/s</p>
      </div><br>

      <%= f.fields_for :mining_rig_miners, @mining_rig_miner do |mining_rig_miners_fields| %>

        <div class="form-group">
          <%= mining_rig_miners_fields.label 'hash rate', class: 'col-md-4 control-label' %>
          <div class="col-md-4">
            <div class="input-group">
              <span class="input-group-addon">Hash Rate:</span>
              <%= mining_rig_miners_fields.number_field :hash_rate, required: "required", class: 'form-control', placeholder: 'Choose from the options above' %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= mining_rig_miners_fields.label 'brand', class: 'col-md-4 control-label' %>
          <div class="col-md-4">
            <div class="input-group">
              <span class="input-group-addon">Brand:</span>
              <%= mining_rig_miners_fields.text_field :brand, required: "required", class: 'form-control', placeholder: 'The brand name for this miner' %>
            </div>
          </div>
        </div>
      <% end %>

      <div class="form-group">
        <label class="col-md-4 control-label" for="button1id">Create</label>
        <div class="col-md-8">
          <%= f.submit class: 'btn btn-success btn-sm' %>
        </div>
      </div>
    <% end %>
  </fieldset>
</form>

app/views/mining_rigs/_mining_rig.html.erb
<div class="thumbnail" style="padding: 0">

  <div class="caption">
    <h2><%= link_to mining_rig.name, user_mining_rig_path(current_user.id, mining_rig), id: 'mining_rig_name' %></h2>
    <% if mining_rig.status %>
      <p>Mining Rig currently mining...</p>
    <% else %>
      <%= button_to 'Start Mining', "/mining_rig/#{mining_rig.id}/miners", {method: 'patch', class: 'btn btn-primary btn-sm'} %>
      <small>(Mining time: 24hrs by default)</small>
    <% end %>
  </div>

  <div class="modal-footer" style="text-align: center">
    <div class="row">
      <div class="col-md-4"><b><%= mining_rig.total_miners %></b><br/><small>Miners</small></div>
      <div class="col-md-4"><b><%= mining_rig.total_cosumption %>W/Hr</b><br/><small>Consumption</small></div>
      <div class="col-md-4"><b><%= mining_rig.total_hashrate %>TH/s</b><br/><small>Hashrate</small></div>
    </div>
    <%= button_to 'Edit', edit_user_mining_rig_path(current_user.id, mining_rig), {method: 'get', class: 'btn btn-primary btn-sm'} %>
  </div>

</div>

app/views/mining_rigs/edit.html.erb
<%= render partial: 'form', locals: {mining_rig: @mining_rig, miners: @miners} %>

app/views/mining_rigs/index.html.erb
<% if current_user.mining_rigs.empty? %>
  <h1>You do not have any mining rigs click below to create a new one</h1>
<% else %>
  <div class="container">
    <%= button_to 'New Mining Rig', new_user_mining_rig_path(current_user), {method: 'get', class: 'btn btn-success btn-lg'} %>
    <br></br>
      <div class="row">
        <ul class="thumbnails list-unstyled">
          <%= content_tag_for(:li, @mining_rigs, class: 'col-md-3') do |mining_rig| %>
            <%= render partial: 'mining_rig', locals: {mining_rig: mining_rig} %>
          <% end %>
        </ul>
      </div>
  </div>
<% end %>

app/views/mining_rigs/new.html.erb
<%= render partial: 'form', locals: {mining_rig: @mining_rig, miners: @miners} %>

app/views/mining_rigs/show.html.erb
<legend><strong><%= @mining_rig.name %></strong></legend>
<%= render 'miners/index', locals: {miners: @mining_rig_miners, mining_rig_miners: @mining_rig_miners} %>