config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'my_devise/omniauth_callbacks', registrations: 'my_devise/registrations' }

  get '/', to: 'application#index'
  # patch '/mining_rig/:id/miners', to: 'miners#mining'
  get '/users/highest_balance', to: 'users#highest_balance', as: 'highest_balance'


  resources :energy_packs
  resources :coins


  resources :users do
    resources :wallets, only: [:show, :update]
    resources :mining_rigs
  end
  patch '/mining_rig/:id/miners', to: 'miners#update'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 ">
        <div class="copyright-text">
          <p class="margin-b-0"><span class="glyphicons glyphicons-electricity"></span><a class="fweight-700" href="#">Miner's Game</a> Powered by: Donnadieu's Studio</a></p>
        </div>
      </div> <!-- End Col -->
      <div class="col-sm-6">
        <ul class="social-link pull-right">
          <li><a href=""><span class="glyphicon glyphicon-flash" aria-hidden="true"></span></a></li>
        </ul>
      </div> <!-- End Col -->
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navcol-1">
        <ul class="nav navbar-nav navbar-right">
          <li role="presentation"> <%= link_to "Profile", user_path(current_user) %> </li>
          <li role="presentation"> <%= link_to "Mining Rigs", user_mining_rigs_path(current_user), id: "mining-rigs-header", "data-id": current_user.id %></li>
          <li role="presentation"> <%= link_to "Rank", highest_balance_path %></li>
          <li role="presentation"> <%= link_to "Get More Energy", energy_packs_path %> </li>
          <li role="presentation"> <%= link_to "Wallet", user_wallet_path(current_user.wallet.id, current_user) %> </li>
          <li role="presentation"> <%= link_to "Log out", destroy_user_session_path, method: :delete%> </li>
         </ul>
       </div>
     </div>
  </nav>
<% end %>
<br><br>

app/views/layouts/_message.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
    </button>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en" class="no-js">
  <head>
    <meta charset="utf-8"/>
    <title>Miner's Game</title>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Anton">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bangers">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.1.1/aos.css">
    <link href="https://fonts.googleapis.com/css?family=Jura" rel="stylesheet">
  </head>
    <body class="bg">
      <%= render 'layouts/header' %>
      <div  id="main" class="container clear-top">
        <%= render 'layouts/message' %>
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
  </body>
</html>